/// Test that a user-defined field named `recursion_limit` does not conflict with the
/// `Message::recursion_limit()` method generated by the derive macro.
use prost::Message;

#[derive(Clone, Copy, Debug, PartialEq, prost::Enumeration)]
pub enum RecursionLimitMode {
    #[prost(number = "0")]
    Default = 0,
    #[prost(number = "1")]
    Unlimited = 1,
}

#[derive(Clone, PartialEq, prost::Message)]
pub struct MessageWithRecursionLimitField {
    /// A user-defined field named `recursion_limit` containing an enum.
    #[prost(enumeration = "RecursionLimitMode", tag = "1")]
    pub recursion_limit: i32,
}

#[test]
fn test_recursion_limit_field_no_conflict() {
    // Verify that the Message trait's `recursion_limit()` method is accessible and returns None.
    assert_eq!(
        <MessageWithRecursionLimitField as Message>::recursion_limit(),
        None
    );

    // Verify that the user-defined field can be set and read without conflict.
    let mut msg = MessageWithRecursionLimitField {
        recursion_limit: RecursionLimitMode::Unlimited as i32,
    };
    assert_eq!(msg.recursion_limit, RecursionLimitMode::Unlimited as i32);

    // Verify round-trip encoding/decoding works correctly.
    let mut buf = alloc::vec::Vec::new();
    msg.encode(&mut buf).unwrap();
    let decoded = MessageWithRecursionLimitField::decode(buf.as_slice()).unwrap();
    assert_eq!(msg, decoded);

    // Modify the field and verify again.
    msg.recursion_limit = RecursionLimitMode::Default as i32;
    assert_eq!(msg.recursion_limit, RecursionLimitMode::Default as i32);
}
